apiVersion: v1
kind: Service
metadata:
  name: nirvana-sales-service
  namespace: nirvana-sales-system

spec:
  type: ClusterIP

  ports:
  - name: sales
    port: 3000
    targetPort: sales
  - name: sales-debug
    port: 3010
    targetPort: sales-debug